# Generated by Django 2.2.3 on 2019-07-01 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(help_text='Enter a habit title here', max_length=200)),
                ('habit_description', models.TextField(help_text='Type your habit description here', max_length=5000)),
                ('habit_numtarget', models.IntegerField(help_text='Enter the number you want to achieve daily for this habit')),
                ('habit_entry', models.IntegerField(help_text='Enter the number you hit for your daily habit')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
                'unique_together': {('user', 'habit_entry')},
            },
        ),
    ]
