# Generated by Django 2.2.2 on 2019-07-01 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habittracker',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='habittracker',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='habittracker',
            name='habit_entry',
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_numachieved', models.IntegerField(help_text='Enter the number you hit for your daily habit')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HabitTracker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
                'unique_together': {('owner', 'habit_numachieved')},
            },
        ),
    ]
