# Generated by Django 2.2.2 on 2019-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190701_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='day_recorded',
            field=models.IntegerField(default=1, help_text='Enter what day you are on for habit tracker (e.g. Day 1, Day 2, ...)'),
        ),
    ]
