# Generated by Django 2.2.2 on 2019-07-02 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailyrecord_day_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
