# Generated by Django 2.2.2 on 2019-07-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20190702_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('owner', 'habit_numachieved')},
        ),
    ]
